name: CI
on: [push, pull_request]
jobs:
  job1:
    runs-on: ubuntu-latest
    name: Pipeline base
    steps:
    - uses: actions/checkout@v4

    - name: Verificar Docker
      run: |
        docker --version
        echo "Docker verificado"
        echo "Instalando kompose"
        curl -L https://github.com/kubernetes/kompose/releases/download/v1.36.0/kompose-linux-amd64 -o kompose
        chmod +x kompose
        sudo mv kompose /usr/local/bin/kompose
        kompose convert -f docker-compose.yml

    - name: Start minikube
      run: |
        minikube start --driver=docker
        eval "$(minikube docker-env)"
        echo "Minikube iniciado"

    - name: Instalando Terraform
      run: |
        curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo apt-key add -
        sudo apt-add-repository "deb [arch=amd64] https://apt.releases.hashicorp.com $(lsb_release -cs) main"
        sudo apt-get update && sudo apt-get install terraform

    - name: Instalando tflint
      run: |
        curl -s https://raw.githubusercontent.com/terraform-linters/tflint/master/install_linux.sh | bash
        echo "tflint instalado"
        
    - name: Instalando terraform-compliance
      run: |
        pip install terraform-compliance
        echo "terraform-compliance instalado"

    - name: Inicializando la sub-red-1
      run: |
        cd monorepo/modules/terraform/network_module
        terraform init
        terraform validate
        terraform plan -out=plan.out
        terraform show -json plan.out > plan.out.json

    - name: Inicializando la sub-red-2
      run: |
        cd monorepo/modules/terraform/network-2_module
        terraform init
        terraform plan -out=tfplan


    - name: Ejecutando docker compose
      run: |
        docker-compose up -d --build
        echo "Docker Compose ejecutado"
        echo "Servicios levantados correctamnete"
