name: CI
on: [push, pull_request]
jobs:
  job1:
    runs-on: ubuntu-latest
    name: Pipeline base
    steps:
    - uses: actions/checkout@v4

    - name: Start minikube
      run: |
        minikube start --driver=docker
        eval "$(minikube -p minikube docker-env --shell bash)"
        echo "Minikube iniciado"

    - name: Instalando Terraform
      run: |
        curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo apt-key add -
        sudo apt-add-repository "deb [arch=amd64] https://apt.releases.hashicorp.com $(lsb_release -cs) main"
        sudo apt-get update && sudo apt-get install terraform

    - name: Instalando terraform-compliance
      run: |
        pip install terraform-compliance
        echo "terraform-compliance instalado"

    - name: Inicializando la sub-red-1
      run: |
        cd monorepo/modules/terraform/network_module
        terraform init
        terraform apply -auto-approve

    - name: Inicializando la sub-red-2
      run: |
        cd monorepo/modules/terraform/network-2_module
        terraform init
        terraform apply -auto-approve
